// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lchdealovxtnxyoucyzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjaGRlYWxvdnh0bnh5b3VjeXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTIwMjksImV4cCI6MjA2NDM2ODAyOX0.hwfiBXsUQlky93kySrurBVzDXYDr5-avLl708B6bch8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);